name: deep-research-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.0
  - pip:
    - langgraph>=0.2.6
    - langchain>=0.3.19
    - langchain-google-genai
    - python-dotenv>=1.0.1
    - langgraph-sdk>=0.1.57
    - langgraph-cli
    - langgraph-api
    - fastapi
    - google-genai
    - uvicorn[standard]
    - pydantic>=2.0.0